[package]
name = "aligngauge-cli"
version = "0.0.0"
description = "Command-line interface for AlignGauge"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
rust-htslib = { version = "1.0.1", default-features = false }

[[bin]]
name = "aligngauge"
path = "src/main.rs"

[lints]
workspace = true
